// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	model "customer/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// CustomerRepository is an autogenerated mock type for the CustomerRepository type
type CustomerRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields:
func (_m *CustomerRepository) Delete() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Get provides a mock function with given fields:
func (_m *CustomerRepository) Get() *[]model.Customer {
	ret := _m.Called()

	var r0 *[]model.Customer
	if rf, ok := ret.Get(0).(func() *[]model.Customer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.Customer)
		}
	}

	return r0
}

// Insert provides a mock function with given fields: customer
func (_m *CustomerRepository) Insert(customer *model.Customer) error {
	ret := _m.Called(customer)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Customer) error); ok {
		r0 = rf(customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Show provides a mock function with given fields:
func (_m *CustomerRepository) Show() *model.Customer {
	ret := _m.Called()

	var r0 *model.Customer
	if rf, ok := ret.Get(0).(func() *model.Customer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Customer)
		}
	}

	return r0
}
